language: python
python:
  - "3.6.10"
  - "3.7.7"
  #- "3.8.3" # currently, the file-io test fails for this version

# install dependencies
install:
  - pip install .[tests]

# run tests
script:
  - pytest tests/