language: python
python:
  - "3.6"
  - "3.7"

# install dependencies
install:
  - python setup.py sdist
  - pip install -r requirements.txt
  - python setup.py install

# run tests
script:
  - pytest tests/